name: Build and Publish JAR

on:
  push:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-jar
          path: target/*.jar
